"""Private local storage. No directory here is mounted as a static URL."""
import os
from pathlib import Path
from uuid import UUID


class LocalPhotoStorage:
    def __init__(self, root: Path):
        self.root = root

    def path(self, key: str) -> Path:
        # Keys are generated by the server. Never use client filenames.
        if not key.endswith('.jpg') or str(UUID(key[:-4])) != key[:-4]:
            raise ValueError('Invalid storage key')
        return self.root / key

    def write(self, key: str, content: bytes):
        self.root.mkdir(parents=True, exist_ok=True, mode=0o700)
        path = self.path(key)
        # Uncommitted rows are invisible, so no reader can see a partial file.
        created = False
        try:
            with path.open('xb') as stream:
                created = True
                os.chmod(path, 0o600)
                stream.write(content)
                stream.flush()
                os.fsync(stream.fileno())
        except Exception:
            if created:
                path.unlink(missing_ok=True)
            raise

    def read(self, key: str) -> bytes:
        return self.path(key).read_bytes()

    def delete(self, key: str):
        self.path(key).unlink(missing_ok=True)


def get_storage() -> LocalPhotoStorage:
    default = Path(__file__).resolve().parents[2] / 'data' / 'photos'
    return LocalPhotoStorage(Path(os.getenv('PHOTO_STORAGE_DIR', str(default))))
